# .goreleaser.yml
# Build customization
builds:
  - binary: factd
    goos:
      - linux
    goarch:
      - amd64
      - 386
archive:
  format: tar.gz
  files:
    - LICENSE
    - README.md

nfpm:
  vendor: Tom Whiston
  homepage: https://github.com/twhiston
  maintainer: Tom Whiston <tom.whiston@gmail.com>

  description: Collect System Facts

  license: Apache 2.0

  formats:
    - deb
    - rpm

  bindir: /usr/bin

  config_files:
    "deployment/factd.service": "/etc/systemd/system/factd.service"

  scripts:
    preinstall: "deployment/preinstall.sh"
    preremove: "deployment/preremove.sh"
