version: '2'

tasks:

  build:
    cmds:
      - go build -o ./dist/factd

  release:
    cmds:
     - goreleaser --snapshot --rm-dist

  release:dist:
    cmds:
      - goreleaser

  lint:
    cmds:
      - gometalinter --vendor ./...

  test:
    cmds:
      - go test ./...

  deps:
    cmds:
      - dep ensure --vendor-only

  deps:update:
    cmds:
      - dep ensure --update

  ci:image:build:
    cmds:
      - docker build -t registry.gitlab.com/twhiston/factd/test-deps:latest .gitlab/

  ci:image:push:
    cmds:
      - docker push registry.gitlab.com/twhiston/factd/test-deps:latest