stages:
  - test
  - build

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - vendor/

variables:
  ORG_PATH: /go/src/github.com/twhiston
  APP_PATH: /go/src/github.com/twhiston/factd

image: registry.gitlab.com/twhiston/factd/test-deps:latest

before_script:
  - mkdir -p ${ORG_PATH}
  - ln -s $PWD  ${ORG_PATH}/
  - cd ${APP_PATH}
  - dep ensure --vendor-only

lint:
  stage: test
  script:
    - gometalinter --vendor --deadline 120s ./...

test:
  stage: test
  script:
    - goverage -v -coverprofile=coverage.out ./... 2> /dev/null
    - godacov -t "${CODACY_TOKEN}" -r ./coverage.out -c "${CI_COMMIT_SHA}" || true
    - go test -race -short $(go list ./... | grep -v /vendor/)
  artifacts:
    paths:
      - coverage.out

build:
  stage: build
  script:
    - goreleaser --snapshot
  artifacts:
    paths:
      - dist